add_newline = false
command_timeout = 2000

[aws]
disabled = true
[gcloud]
disabled = true
[time]
disabled = false
time_format = "%Y/%m/%d %H:%M"
[directory]
truncation_length = 10
truncate_to_repo = false
[username]
style_user = "white bold"
disabled = false
show_always = true
[hostname]
ssh_only = false
format = "[$hostname](bold red) "
disabled = false
[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold red"
format = "[$output]($style) "